version: '3.5'
services:
  api1: &api # API - Instância 01
    image: api
    hostname: api1
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

  api2: # API - Instância 01
    <<: *api
    hostname: api2

  nginx: # Load Balancer
    image: nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

  db: # Banco de dados
    image: postgres
    hostname: postgres
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: ['postgres', '-c', 'max_connections=500']
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: '1.05'
          memory: '2.1GB'
